### ISSUE TITLE
ошибка при установке через Realm(BepInEx)

### ISSUE THREAD

**Issue by Sharaj00** [thalber/RW-RU#1]
название треда я думаю исчерпывающе описывает проблему

**Comment by thalber** [comment]
Я не пользовался Realm, опишите предпринятые шаги и полученную ошибку.

**Comment by Sharaj00** [comment]
попробуй установить через реалм, куда нагляднее будет самостоятельно воспроизвести ошибку
следовал гайду
ошибка после запуска игры, пишет что то по типу не удалось запустить с модами, перезапустите игру через меню  модов. такая ошибка появляется обычно если какой то из модов проблемный

**Comment by thalber** [comment]
Хотите получить помощь - предоставляйте информацию. 
Мне нужна версия Realm, список модов и logOutput.log с запуска, где произошла ошибка.

**Comment by Sharaj00** [comment]
я русификатором не пользуюсь, просто обнаружил и посчитал нужным сообщить что имеется проблема
но раз уж без моей помощи не обойтись
реалм актуальной версии
[LogOutput.log](https://github.com/thalber/RW-RU/files/8532304/LogOutput.log)
[prefs.txt](https://github.com/thalber/RW-RU/files/8532311/prefs.txt)

**Comment by Sharaj00** [comment]
я предполагаю что CUMмуникейшон модуль пытается найти папку Language в папке с модами, но реалм их конвертирует в свой формат и выпиливает оттуда

**Comment by thalber** [comment]
Language случайно не распакована внутрь bepinex/plugins/Language/?

**Comment by Sharaj00** [comment]
имеешь ввиду итоговый путь "bepinex/plugins/Language/Language"?
нет

**Comment by Sharaj00** [comment]
лол, сам же предположил и только сейчас дошло, что можно папке поставить свойство "только для чтения"
и это сработало
теперь ошибок нет, русик пашет

**Comment by thalber** [comment]
передал данные о проблеме @Dual-Iron
